### ISSUE TITLE
[뉴스] 클릭했을 때 url로 이동하도록 라우팅

### ISSUE THREAD

**Issue by jsontype** [jsontype/generalapp#7]
a 태그를 사용
무비앱과 동일한 형태로 후버 핑크 주고.

**Comment by sgh99m** [comment]
개요
무비앱과 동일한 형태로 타이틀에 후버 핑크추가와 타이틀 클릭시 url로 이동하도록 라우팅

테스트
후버핑크가 제대로 적용됬는지 확인과 클릭시 URL로 이동되는지 확인
